### ISSUE TITLE
Would this be possible to finetune on a weaker gpu like a t4?

### ISSUE THREAD

**Issue by VatsaDev** [jzhang38/TinyLlama#11]
When a finetuneable version of this model comes out, will we be able to fine-tune it on a Google colab T4 gpu?

**Comment by jzhang38** [comment]
T4 has 16GB GPU RAM. I'd say that is plenty for TinyLlama.

**Comment by VatsaDev** [comment]
Tiny LLama full version? I thought the 4bit quant version would be a safe finetune on colab T4, but the full checkpoint takes around 13.2GB just to inference, and most models I've worked with take around double the amount of RAM to finetune compared to inference. 

![Screen Shot 2023-09-07 at 9 08 51 PM](https://github.com/jzhang38/TinyLlama/assets/71975550/8b77460a-3abc-4559-b53c-8ca6ae01a5b0)

**Comment by jzhang38** [comment]
You may need to use lora/qlora

**Comment by TapendraBaduwal** [comment]
@jzhang38 How to train this tiny model ? 
Is this same as training by using BitsandBytes and SFT ?

Can you share the training source or idea ?

**Comment by jzhang38** [comment]
@TapendraBaduwal You can safely ingnore this warning.

**Comment by TapendraBaduwal** [comment]
@jzhang38 I want to train Tinly llama model PY007/TinyLlama-1.1B-step-50K-105b with databricks-dolly-15k.jsonl dataset format.
And Can we Finetuning using BitsandBytes and SFT and use lora/qlora ?

**Comment by TapendraBaduwal** [comment]
@jzhang38 I have  load datasets and Finetuning using BitsandBytes and SFT and use lora/qlora .

Since i have train model with dataset format as {"instruction": "question here.", "context": "context here.", "category": "category here", "response": "{ABC:XYZ}".... My all response data is in json type but model give me in only in text response.
Is am i wrong with  training datasets format ?


def format_dolly(sample):
    instruction = f"<s>[INST] {sample['instruction']}"
    context = f"Here's some context: {sample['context']}" if len(sample["context"]) > 0 else None
    response = f" [/INST] {sample['response']}"
    # join all the parts together
    prompt = "".join([i for i in [instruction, context, response] if i is not None])
    return prompt

# template dataset to add prompt to each sample
def template_dataset(sample):
    sample["text"] = f"{format_dolly(sample)}{tokenizer.eos_token}"
    return sample

dataset = load_dataset("json", data_files="/content/databricks-dolly-15k.jsonl", split="train")
dataset = dataset.map(template_dataset, remove_columns=list(dataset.features))
dataset

**Comment by VatsaDev** [comment]
Fixed with the new release,
