### ISSUE TITLE
Current state of TinyLlama

### ISSUE THREAD

**Issue by tkforall** [jzhang38/TinyLlama#72]
A few ideas.

1. If at all feasible, I'd seriously consider releasing the 'faulty' 1.5T checkpoint and restarting the project from scratch. The first 0.5 trillion tokens were also trained with the wrong learning rate, so these missteps might compound and really hurt the quality of the final product. If you restart you can also apply all the tricks and tweaks you've learned thus far, and do so from the very start.

2. You could also continue on from 1.5T and save your funds for a v2 of TinyLlama or some other project. Given where you are right now, there shouldn't be _that_ much of a difference between continuing on from 1.0T vs 1.5T.

Sorry if my suggestions are too intrusive or nonsensical. **Regardless of which approach you take, best of luck with TinyLlama!**

**Comment by jzhang38** [comment]
@tkforall Thanks for your thoughtful suggestions! We had some intense internal discussions and ideas similar to yours were raised. We eventually opted to roll back to the 1.0T checkpoint and continue due to our limited budget. We may plan to restart training from scratch when we have access to more compute in the future.  

The faulty 1.5T checkpoint is released [here](https://huggingface.co/TinyLlama/tinyLlama-intermediate-checkpoints/tree/step-715k-token-1499B).
